In [3]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense, Conv2D, MaxPool2D, Dropout

from tensorflow.keras.preprocessing.image import ImageDataGenerator

print(tf.__version__)

2.10.1


In [4]:
img_width = 128
img_height = 128

In [ ]:
!pip install split_folders

In [5]:
import splitfolders

In [ ]:
splitfolders.ratio("data3a/training", output="output", seed=1337, ratio=(.8, .2), group_prefix=None) 

Copying files: 0 files [00:00, ? files/s]

Copying files: 1383 files [00:04, 300.75 files/s]


In [8]:
test_datagen = ImageDataGenerator(rescale=1./255)

In [ ]:

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_gen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=30,
    zoom_range=0.3,
    horizontal_flip=True,
    brightness_range=[0.7,1.3]
)

val_gen = ImageDataGenerator(rescale=1./255)

train_data = train_gen.flow_from_directory(
    "C:/datascience/workspace/data3a/training/",
    target_size=(128,128),
    batch_size=32,
    class_mode='categorical'
)

val_data = val_gen.flow_from_directory(
    "C:/datascience/workspace/data3a/validation/",
    target_size=(128,128),
    batch_size=32,
    class_mode='categorical'
)



Found 1383 images belonging to 3 classes.
Found 248 images belonging to 3 classes.


In [10]:
print("Class names:", train_data.class_indices)
class_names = list(train_data.class_indices.keys())
print("Class names:", class_names)

Class names: {'01-minor': 0, '02-moderate': 1, '03-severe': 2}
Class names: ['01-minor', '02-moderate', '03-severe']


In [11]:

train_data.filenames[:5], train_data.filenames[-5:]

(['01-minor\\0001.JPEG',
  '01-minor\\0002.JPEG',
  '01-minor\\0003.JPEG',
  '01-minor\\0004.JPEG',
  '01-minor\\0005.JPEG'],
 ['03-severe\\images - 2022-12-13T215957.415.jpeg',
  '03-severe\\images - 2022-12-13T215957.493.jpeg',
  '03-severe\\images - 2022-12-13T215957.532.jpeg',
  '03-severe\\images - 2022-12-13T215957.643.jpeg',
  '03-severe\\images - 2022-12-13T215957.811.jpeg'])

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,BatchNormalization,MaxPooling2D,Flatten,Dense,Dropout

model =Sequential([
Conv2D(32, (3,3), activation='relu', input_shape=(128,128,3)),
BatchNormalization(),
MaxPooling2D(2,2),
Conv2D(64, (3,3), activation='relu'),
BatchNormalization(),
MaxPooling2D(2,2),

Conv2D(128, (3,3), activation='relu'),
BatchNormalization(),
MaxPooling2D(2,2),

Flatten(),
Dense(256, activation='relu'),
Dropout(0.5),

Dense(3, activation='softmax')
])
model
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 126, 126, 32)      896       
                                                                 
 batch_normalization (BatchN  (None, 126, 126, 32)     128       
 ormalization)                                                   
                                                                 
 max_pooling2d (MaxPooling2D  (None, 63, 63, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 61, 61, 64)        18496     
                                                                 
 batch_normalization_1 (Batc  (None, 61, 61, 64)       256       
 hNormalization)                                                 
                                                        

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 126, 126, 32)      896       
                                                                 
 batch_normalization (BatchN  (None, 126, 126, 32)     128       
 ormalization)                                                   
                                                                 
 max_pooling2d (MaxPooling2D  (None, 63, 63, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 61, 61, 64)        18496     
                                                                 
 batch_normalization_1 (Batc  (None, 61, 61, 64)       256       
 hNormalization)                                                 
                                                        

In [ ]:


import tensorflow as tf
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)


In [7]:
import numpy as np
from tensorflow.keras.preprocessing import image

In [13]:
history = model.fit(
    train_data,
    validation_data=val_data,
    validation_steps=len(val_data),
    epochs=10,
 
)

Epoch 1/10
44/44 [==============================] - 29s 648ms/step - loss: 0.9123 - accuracy: 0.5560 - val_loss: 1.0687 - val_accuracy: 0.5040
Epoch 2/10
44/44 [==============================] - 29s 647ms/step - loss: 0.9009 - accuracy: 0.5662 - val_loss: 0.9071 - val_accuracy: 0.5766
Epoch 3/10
44/44 [==============================] - 29s 662ms/step - loss: 0.9128 - accuracy: 0.5568 - val_loss: 0.9187 - val_accuracy: 0.5363
Epoch 4/10
44/44 [==============================] - 29s 651ms/step - loss: 0.8924 - accuracy: 0.5813 - val_loss: 0.8614 - val_accuracy: 0.6371
Epoch 5/10
44/44 [==============================] - 29s 650ms/step - loss: 0.8704 - accuracy: 0.5777 - val_loss: 0.8094 - val_accuracy: 0.6008
Epoch 6/10
44/44 [==============================] - 29s 652ms/step - loss: 0.8791 - accuracy: 0.5691 - val_loss: 0.8196 - val_accuracy: 0.6008
Epoch 7/10
44/44 [==============================] - 29s 652ms/step - loss: 0.8777 - accuracy: 0.5589 - val_loss: 0.8560 - val_accuracy: 0.6129

In [14]:
class_names=['Minor','Moderate','Severe']

In [15]:
test_image = image.load_img('C:/datascience/workspace/data3a/validation/01-minor/0006.JPEG',target_size=(128,128))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image,axis=0)
result = model.predict(test_image)
result

1/1 [==============================] - 0s 105ms/step


array([[1., 0., 0.]], dtype=float32)

In [16]:
test_image = image.load_img('C:/datascience/workspace/data3a/validation/03-severe/0001.JPEG',target_size=(128,128))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image,axis=0)
result = model.predict(test_image)
result

1/1 [==============================] - 0s 29ms/step


array([[0.00000e+00, 1.00000e+00, 3.46949e-29]], dtype=float32)

In [17]:
test_image = image.load_img('C:/datascience/workspace/data3a/validation/03-severe/0001.JPEG',target_size=(128,128))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image,axis=0)
result = model.predict(test_image)
result

1/1 [==============================] - 0s 27ms/step


array([[0.00000e+00, 1.00000e+00, 3.46949e-29]], dtype=float32)

In [18]:
# from keras.models import load_model
from tensorflow.keras.models import load_model
model_json = model.to_json()
with open("malaria_model.json", "w") as json_file:
    json_file.write(model_json)

model.save('my_model.h5')  # creates a HDF5 file 'my_model.h5'

# returns a compiled model
# identical to the previous one
model = load_model('my_model.h5')

In [19]:
# from keras.models import model_from_json
from tensorflow.keras.models import model_from_json

json_file = open('malaria_model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
loaded_model.load_weights("my_model.h5")
print("Loaded model from disk")

Loaded model from disk


In [20]:
loaded_model.compile(optimizer='adam', loss='category_crossentropy', metrics = ['accuracy'])

In [21]:
score = model.evaluate(val_data, steps=len(val_data))

# Print the evaluation score
print('Test loss:', score[0])
print('Test accuracy:', score[1])

8/8 [==============================] - 1s 120ms/step - loss: 0.8620 - accuracy: 0.5847
Test loss: 0.8620002865791321
Test accuracy: 0.5846773982048035


In [22]:
score

[0.8620002865791321, 0.5846773982048035]

In [23]:
loaded_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 126, 126, 32)      896       
                                                                 
 batch_normalization (BatchN  (None, 126, 126, 32)     128       
 ormalization)                                                   
                                                                 
 max_pooling2d (MaxPooling2D  (None, 63, 63, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 61, 61, 64)        18496     
                                                                 
 batch_normalization_1 (Batc  (None, 61, 61, 64)       256       
 hNormalization)                                                 
                                                        

In [24]:
test_image = image.load_img('C:/datascience/workspace/data3a/validation/03-severe/0001.JPEG',target_size=(128,128))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image,axis=0)
result = model.predict(test_image)
result

1/1 [==============================] - 0s 73ms/step


array([[0.00000e+00, 1.00000e+00, 3.46949e-29]], dtype=float32)

In [25]:


class_names = ['Minor', 'Moderate', 'Severe']  # must match training order

class_id = result.argmax()
prediction = class_names[class_id]
confidence = result[0][class_id]

print("Prediction:", prediction)
print("Confidence:", confidence)

Prediction: Moderate
Confidence: 1.0


In [ ]:

if class_id == 2:
    prediction = "Severe"
elif class_id == 1:
    prediction = "Moderate"
else:
    prediction = "Minor"

print(prediction)

Moderate


In [ ]:
import cv2
import numpy as np
from tensorflow.keras.models import load_model

cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    if not ret:
        break

    img = cv2.resize(frame, (128, 128))
    img = img / 255.0
    img = np.expand_dims(img, axis=0)

    preds = model.predict(img)
    class_id = np.argmax(preds)
    confidence = preds[0][class_id]

    label = f"{class_names[class_id]} ({confidence*100:.2f}%)"

    cv2.putText(frame, label, (20, 40),
                cv2.FONT_HERSHEY_SIMPLEX, 1,
                (0, 255, 0), 2)

    cv2.imshow("Car Damage Detection", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()


1/1 [==============================] - 0s 88ms/step
